version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: node-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-changemechangemechangemechangeme}
      - N8N_USER_FOLDER=/home/node/.n8n
      # Configuração para usar nodes customizados
      - N8N_CUSTOM_EXTENSIONS=/app/custom
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5678/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/app/custom/n8n-nodes-notebooklm
      - ./package.json:/app/custom/n8n-nodes-notebooklm/package.json
    networks:
      - n8n-network

volumes:
  n8n_data:

networks:
  n8n-network:
    driver: bridge